### ISSUE TITLE
Button on web layout is not looking good I want to work on that issue

### ISSUE THREAD

**Issue by arunsingh009** [arunn0909/TemplatesNation#20]

**Comment by arunn0909** [comment]
go for it

**Comment by Igdtuwresource** [comment]
@arunn0909 can you please assign this to me?

**Comment by arunn0909** [comment]
Actually i have assigned it to someone else but you can work on it and merge will be done on first come first merge basis

**Comment by arunsingh009** [comment]
@Igdtuwresource Sorry for this time I won 👍✌
